services:
  - type: web
    name: n8n-video
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-video.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
