services:
  - type: web
    name: locnutri-n8n
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: locnutri@2024
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        value: https://locnutri-n8n.onrender.com
